CREATE TABLE IF NOT EXISTS stock (
    id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    current_price FLOAT NOT NULL,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);